---
- name: Make sure the required directory exists
  hosts: all
  gather_facts: false
  
  tasks: 

    - name: Make sure the required directory exists
      file:
        path: "{{path}}/backup"
        state: directory
      check_mode: no

- name: backup EOS conf 
  hosts: all
  connection: httpapi
  gather_facts: false
  
  tasks:

    - name: backup EOS conf 
      eos_config:
        backup: yes
        backup_options:
          dir_path: "{{path}}/backup"
